version: "2"

services:
  postgres:
    image: postgres:15-alpine
    container_name: satellite_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: satellite
    ports:
      - "5432:5432"

  app:
    container_name: satellite_app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://satellite_db:5432/satellite
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
